# Site settings
title: Aurelien
email: aurel427@gmail.com
description: Professional portfolio
baseurl: ""
url: "http://aurelien-ldp.github.io"
github_username: aurelien-ldp

# Build settings
markdown: kramdown
