# Site settings
title: Aurelien Louis Dit Picard
email: aurelien.louisditpicard@epitech.eu
description: Numeric Portfolio
baseurl: ""
url: "http://aurelien-ldp.github.io"
github_username: aurelien-ldp

# Build settings
markdown: kramdown
